<?php

/**
 * Implements hook_form_alter().
 */
function taxonomy_field_body_class_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'field_ui_field_edit_form') {
    if (isset($form['#field']['type']) && $form['#field']['type'] == 'taxonomy_term_reference') {
      $form['instance']['as_body_class'] = array(
        '#type' => 'checkbox',
        '#title' => t('Add as body class'),
        '#default_value' => $form['#instance']['as_body_class'],
        '#description' => t('On enabling this, the value(s) of this field, if present will be added as class(es) to the body.'),
        '#weight' => -10,
      );
    }
  }
}
