<?php

/**
 * @file
 * Adds a class to the content body tag with the terms the node is tagged with.
 */

/**
 * Implements hook_form_alter().
 */
function taxonomy_field_body_class_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'field_ui_field_edit_form') {
    if (isset($form['#field']['type']) && $form['#field']['type'] == 'taxonomy_term_reference') {
      $form['instance']['as_body_class'] = array(
        '#type' => 'checkbox',
        '#title' => t('Add as body class'),
        '#default_value' => $form['#instance']['as_body_class'],
        '#description' => t('On enabling this, the value(s) of this field, if present will be added as class(es) to the body.'),
        '#weight' => -10,
      );
    }
  }
}

/**
 * Implements hook_preprocess_html().
 */
function taxonomy_field_body_class_preprocess_html(&$variables) {
  if (!path_is_admin(current_path())) {
    $node = menu_get_object();
    if (is_object($node) && isset($node->nid)) {
      $content_type_fields = field_info_instances('node', $node->type);
      $field_class_arr = array();
      foreach ($content_type_fields as $field) {
        if (isset($field['as_body_class']) && $field['as_body_class']) {
          $field_name = $field['field_name'];
          $field_values = field_get_items('node', $node, $field_name);
          foreach ($field_values as $term) {
            $machine_readable = strtolower($term['taxonomy_term']->name);
            $machine_readable = preg_replace('@[^a-z0-9_]+@', '-', $machine_readable);
            $field_class_arr[] = $machine_readable;
          }
        }
      }
      $variables['classes_array'] = array_merge($variables['classes_array'], $field_class_arr);
    }
  }
}
